### ISSUE TITLE
Pick sample not working

### ISSUE THREAD

**Issue by Hurleyworks** [shocker-0x15/OptiX_Utility#11]
Hello!

The new Pick sample does not work on my system. The sample compiles and runs but after 2 render iterations it hits (in Debug mode) an "out of range" assert in std::vector.  In Release mode the sample crashes.  If I try to debug, it looks like the assert is triggered on line 1185 of pick_main.cpp because pickInfo.instanceID is an invalid number.

Optix 7.2
Cuda 11.2
RTX 2070 SUPER  vs 460.89

![Pick_sample_crash](https://user-images.githubusercontent.com/8120255/103709482-a0603580-4f80-11eb-8148-b44628a05cec.jpg)

**Comment by shocker-0x15** [comment]
It seems like I wrote something stupid code.
I hope the fixed code runs correctly.
Thanks for the report!

**Comment by Hurleyworks** [comment]
Working as expected now.  Thanks!

**Comment by Hurleyworks** [comment]
Oops one more little thing.  The app Window header says "Scene Edit" instead of "Pick". :)
