### ISSUE TITLE
Assimp not working in scene_edit sample

### ISSUE THREAD

**Issue by Hurleyworks** [shocker-0x15/OptiX_Utility#14]
Hi,

I've compiled OptiX_Utility using cmake. There seems to be a problem when trying to load any  .OBJ file using Assimp in the scene_edit sample . Assimp fails with this message:

ai_assert failure in D:\ActiveWorks\OpenSource\rendering\OptiX_Utility\ext\assimp\code\Common\Importer.cpp(812): _ValidateFlags(pFlags)

**Comment by shocker-0x15** [comment]
Hello,
Thanks for the report.

I couldn't confirm the issue with Release build but could with Debug.
I'll investigate.

**Comment by shocker-0x15** [comment]
Fixed.
I used an invalid combination of Assimp importer flags.

**Comment by Hurleyworks** [comment]
Confirmed fixed. Thank you!
