### ISSUE TITLE
Some samples crash in Debug mode only

### ISSUE THREAD

**Issue by Hurleyworks** [shocker-0x15/OptiX_Utility#18]
Greeting!

These samples crash in  the latest OptiX_Utility in debug mode only. I couldn't learn anything running the NSight cuda debugger
pick
texture
material_sets
multi_level_instancing

Here's the error message
[ 2][       ERROR]: Error recording event to prevent concurrent launches on the same OptixPipeline (CUDA error string: unspecified launch failure, CUDA error code: 719)
Error recording resource event on user stream (CUDA error string: unspecified launch failure, CUDA error code: 719)

OptiX 8.0
Cuda 12.2
Geforce RTX 3090 driver 537.34 ( crashed in previous driver too )
Windows 11 Pro

**Comment by Hurleyworks** [comment]
Oops. I just noticed you might have reported the same problem on the OptiX forum so feel free to close this if that is the case.

**Comment by shocker-0x15** [comment]
Hello, thanks for the report!

I have the crashes on exactly the same samples (while I reported the issue based on modifying single_level_instancing.)
I guess this is OptiX/driver-side issue since those samples has basically been healthy until now.
Let's wait some response from OpitX dev team...

**Comment by shocker-0x15** [comment]
It looks that the issue has been found in OptiX and will be fixed in a future R545 driver.
I'll close this issue once I confirm the fix in the future.

**Comment by Hurleyworks** [comment]
I can confirm this issue seems to be fixed in driver 545.84

I can also confirm the crash on exit problem you posted on the OptiX forum using the repro you provided.
https://forums.developer.nvidia.com/t/crash-at-app-termination-nvcuda64-dll/269877

**Comment by shocker-0x15** [comment]
This particular issue has been resolved.
I’m closing.
