### ISSUE TITLE
Compilation files

### ISSUE THREAD

**Issue by nezix** [shocker-0x15/OptiX_Utility#8]
Hi,

Could you please update the Visual Studio solution file or CMake files for compiling this project ?

Thanks for sharing !

**Comment by shocker-0x15** [comment]
Hello,

Writing CMake is actually my TODO.
There are already Visual Studio solution files for the samples. Didn't they work for your environment?
It worked on my environment as of today:
- Windows 10 (1909) & Visual Studio 2019 (16.7.7)
- Core i9-9900K, 32GB, RTX 3080 10GB
- NVIDIA Driver 457.09

**Comment by nezix** [comment]
Sorry, I didn't see the file in the root folder I wrongly assumed it was not there.
Nice setup btw :)

It works fine on a 2080 Super, thanks !

**Comment by shocker-0x15** [comment]
Great!

**Comment by shocker-0x15** [comment]
This is just for your information.
Please be careful to install CUDA 11.1 with Nsight VSE.
- Visual Studio 2019 became too slow after installing CUDA 11.1
https://forums.developer.nvidia.com/t/visual-studio-2019-became-too-slow-after-installing-cuda-11-1/155952/25
